#define WORKDIR "/etc/easygcoder"
#define VERSION "0.1.6"
#define TOOL_D 0.2
#define TOOL_CH_HEIGHT 70
#define SVG_M 10
#define SVG_WIDTH 1920
#define SVG_HEIGHT 1080
#define SVG_MARGIN 50
#define DRILL_SAFE 5
#define DRILL_START 0
#define DRILL_DEEP -2.4
#define DRILL_STEP -0.6
#define DRILL_FEED 50
#define MILLING_SAFE 5
#define MILLING_START 0.1
#define MILLING_DEEP -0.1
#define MILLING_STEP -0.2
#define MILLING_FEED 100
#define CONFIGPATH "/etc/easygcoder/easygcoder.conf"
